# 1.3 多个yml文件配置
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot_test
  username: root
  password: xj

#配置tomcat的端口
server:
  port: 80

#设置日志记录级别
logging:
  level:
    cn.xujian: debug
    org.springframework: info

#配置数据库连接池参数
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_test
    username: root
    password: xj
  redis:
    host: localhost
    port: 6379

mybatis:
#  配置实体类别名包路径
  type-aliases-package: cn.xujian.pojo
#  映射文件路径
#  mapper-locations: classpath:mapper/*.xml
#日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl